# Generated by Django 6.1 on 2026-10-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_settings_post', models.DateField()),
                ('media_in_post', models.BooleanField()),
                ('video_in_post', models.BooleanField()),
                ('links_in_post', models.BooleanField()),
                ('links_post', models.BooleanField()),
                ('main_photo_post', models.BooleanField()),
                ('main_video_post', models.BooleanField()),
            ],
        ),
    ]
